version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch
    command: meilisearch
    environment:
      MEILI_ENV: ${MEILI_ENV:-development}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"
    