/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    "color-picker": colorPicker,
    graphql: graphql,
    seo: seo,
    "users-permissions": usersPermissions,
    "config-sync": configSync,
    "duplicate-button": duplicateButton,
    "import-export-entries": importExportEntries,
    meilisearch: meilisearch,
  },
});
